# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-04-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_token', models.CharField(max_length=200, null=True)),
                ('starting_user', models.BigIntegerField(help_text='the Twitter id of the user', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('crawl_friends', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='twitter.CrawlerTasks')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('tweet_id', models.BigIntegerField(null=True)),
                ('retweet_count', models.IntegerField(default=0)),
                ('tweet_created_date', models.DateTimeField(blank=True, null=True)),
                ('like_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('twitter_id', models.BigIntegerField(null=True)),
                ('twitter_handle', models.CharField(max_length=100, null=True)),
                ('followers_count', models.IntegerField(null=True)),
                ('friends_count', models.IntegerField(null=True)),
                ('listed_count', models.IntegerField(null=True)),
                ('statuses_count', models.BigIntegerField(null=True)),
                ('twitter_user_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(related_name='twitter_followers', to='twitter.TwitterUser')),
                ('friends', models.ManyToManyField(related_name='twitter_friends', to='twitter.TwitterUser')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tweets', to='twitter.TwitterUser'),
        ),
    ]
